menu:
  Home: /
  Archives: /archives

widgets:
- search

cover:
  enable: true
  url: http://pic19.nipic.com/20120328/1619719_152525164116_2.jpg

excerpt_link: Read More

full_format: 'ddd, MMM D YYYY, h:mm:ss a'

addthis:
  enable: true
  pubid:
  facebook:
  twitter:
  google: true
  pinterest:

fancybox: true

google_analytics: UA-368771XX-X
rss:

comment_provider: duoshuo

# Duoshuo comment
duoshuo:
  short_name: jeffy

social:
  github: https://github.com/JeffyWang
  weibo: http://weibo.com/wjf1027
  google_plus: 
  linkedin: http://www.linkedin.com/profile/view?id=324679835&trk=nav_responsive_tab_profile_pic

auto_change:
  enable: true
